import '@/style/globals.css'
import { Inter } from 'next/font/google'
// import connectDB from "@/DB/mongoose"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Root',
  description: 'Generated by create next app',
}
// 连接数据库
// connectDB();
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}